name: Test

on: workflow_call

jobs:
  install:
    # runs install first so that other jobs can install dependencies from cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

  tests:
    runs-on: ubuntu-latest
    needs: install
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Run Tests
        run: pnpm test:ci
